name: Build and Push dist

on:
  release:
    types: [created]

# 使用并发取消任何当前作业或运行
concurrency:
  group: ${{github.ref}}
  cancel-in-progress: true

env:
  NAME: cms-dev
  ACTIVE: dev
  IMAGE: registry.digitalocean.com/seechange/cms:dev
  PORT: 3000
  OUT_PORT: 13003

jobs:
  action_trigger:
    if:  startsWith(github.ref, 'refs/tags/cms-frontend/') 
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps: 
      - name: get tag info
        uses: MashyChen/tag-parse-action@main
        with:
          githubToken: ${{ secrets.ACCESS_TOKEN }}

      - name: checkout code
        uses: actions/checkout@v4
        with:
          repository: SeeChange-edu/${{ env.REPOSITORY }}
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: ${{ env.BRANCH }}

      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: yarn

      - name: Build Yarn
        run: |
            yarn --frozen-lockfile
            cp ./env/${{ env.ACTIVE }}.env .env.production
            yarn build

          